dishes/urls.py
from django.urls import path

from . import views

app_name='dishes'


urlpatterns = [
    path('', views.index, name='index'),
    path('dishes/', views.leaderboard, name='leaderboard'),
    path('add-dish/', views.dishAdd, name='dishAdd'),
    path('dish_details/<int:dish_Id>', views.dish_details, name='dish_details'),
    path('hotel/add/', views.hotelAdd, name='hotelAdd'),  # Add this line
    # path('top-dishes-chart/', views.top_dishes_chart, name='top_dishes_chart'),
    path('graph/', views.dish_graph, name='dish_graph'),  # Add Graph URL

]

foodcourt/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('dishes.urls',)),
    path('', include('users.urls',)),
    path('customer/', include('customer.urls',)),
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls',)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('payment-form/', views.payment_form, name='payment_form'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('payment-success/', views.payment_success, name='payment_success'),  # Added payment success path
    path('payment-failure/', views.payment_failure, name='payment_failure'),  # Added payment success path
]

users/urls.py
from django.urls import path

from . import views

app_name='users'


urlpatterns = [
    path('login/', views.f_login, name='f_login'),
    path('sign_up/', views.f_sign_up, name='f_sign_up'),
    path('logout/',views.logoutUser,name='logout')
    
]

payment/models.py
from django.db import models

class Payment(models.Model):
    order_id = models.CharField(max_length=100)  # Assuming you have an external order ID you wish to track
    razorpay_payment_id = models.CharField(max_length=255, unique=True)  # Razorpay's payment ID
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # Amount paid
    is_successful = models.BooleanField(default=False)  # Payment status
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp of the payment

    def __str__(self):
        return f"Payment {self.razorpay_payment_id} - {'Successful' if self.is_successful else 'Failed'}"

payment/views.py
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
#from dishes.models import Hotel, dish
#import razorpay
import json

# Razorpay client initializa
# views.py

from django.shortcuts import render, redirect
from django.http import HttpResponse

def payment_form(request):
    amount = request.GET.get('amount', 0)
    return render(request, 'paymentnew.html', {'amount': amount})

def payment(request):
    return render(request, 'payment.html')

def process_payment(request):
    if request.method == 'POST':
    
        card_number = request.POST.get('card_number')
        expiry_date = request.POST.get('expiry_date')
        cvv = request.POST.get('cvv')
        amount = request.POST.get('amount')

        import random
        payment_success = True  
        
        if payment_success:
            return redirect('payment_success')  # Pass amount as a URL parameter
        else:
            return redirect('payment_failure')

    return HttpResponse("Invalid request", status=400)

def payment_success(request):
    return render(request, 'success.html')

def payment_failure(request):
    return render(request, 'failure.html')

templates/dish_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>Add Dishes</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Ubuntu:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-image: url("{% static 'img/background.png' %}");
            color: white;
            
            
        }
        #back {
            background-color: transparent;
            border: none;
            cursor: pointer;
            margin: 20px;
        }
        #back:hover {
            color: #007bff;
        }
        .container {
            margin: 50px auto;
            padding: 20px;
            border: 2px solid black;
            border-radius: 10px;
            background-image: linear-gradient(to top,rgba(0, 0, 0, 0.297),rgba(0, 0, 0, 0.297));
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            opacity:20px;
            
        }
        h1 {
            text-align: center;
            padding-bottom: 20px;
            color: #ff8800;
            font-weight: 700;
        }
        .btn-primary {
            background-color: #ff8800;
            border: none;
        }
        .btn-primary:hover {
            background-color: #e67e22;
        }
        .form-check-input:checked {
            background-color: #ff8800;
            border-color: #ff8800;
        }
        .alert {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    
    <div class="container">
      <a id="back" onClick="javascript:history.go(-1);">
        <i class="fa-solid fa-2x fa-chevron-left" style="  color: #ff8800;"></i>
    </a>
        <h1>Add Dishes</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="hotel">Select Hotel</label>
                <select class="form-control" name="hotel" id="hotel" required>
                    <option value="" disabled selected>Select a hotel</option>
                    {% for hotel in hotels %}
                        <option value="{{ hotel.hotel_Id }}">{{ hotel.h_Name }}</option>
                    {% endfor %}
                </select>
            </div></br>
            <div class="row mb-3">
                <div class="col-7">
                    <div class="form-group">
                        <label for="dName">Dish Name</label>
                        <input type="text" class="form-control" name="dName" id="dName" placeholder="e.g., Poha" required>
                    </div>
                </div>
                <div class="col-5">
                    <div class="form-group">
                        <label for="dPrice">Dish Price</label>
                        <input type="number" class="form-control" name="dPrice" id="dPrice" placeholder="e.g., 50" required>
                    </div>
                </div>
            </div>
            <div class="form-group mb-3">
                <label for="dDescription">Dish Description</label>
                <textarea class="form-control" name="dDescription" id="dDescription" rows="3"></textarea>
            </div>
            <div class="form-group mb-3">
                <label for="dIngredients">Dish Ingredients</label>
                <textarea class="form-control" name="dIngredients" id="dIngredients" rows="3"></textarea>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="dtype" id="inlineRadio1" value="Veg" required>
                        <label class="form-check-label" for="inlineRadio1">Veg</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="dtype" id="inlineRadio2" value="Non-Veg" required>
                        <label class="form-check-label" for="inlineRadio2">Non-Veg</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="dPhoto">Upload Dish Photo</label>
                        <input type="file" class="form-control-file" name="dPhoto" id="dPhoto">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary">Add Dish</button>
                </div>
            </div>
        </form>

        <div class="row">
            <div class="col">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/failure.html
<!-- templates/mock_payment_failure.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Failed</title>
</head>
<body>
    <h2>Payment Failed</h2>
    <p>There was an issue processing your payment. Please try again.</p>
    <a href="{% url 'payment_form' %}">Try Again</a>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}

    <title>Food Court</title>
    <link rel="icon" href="{% static 'img/final32.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <style>
        :root {
            --primary-color: #02AA14;
            --secondary-color: #343434;
            --background-color: #f9f9f9;
            --light-grey: #afafaf;
            --white: #FFFFFF;
        }

        body {
            background-color: var(--background-color);
            overflow-y: auto;
        }

        .btn {
            width: 16rem;
            background-color: var(--primary-color);
            border-radius: 16px;
            color: var(--white);
            font-family: 'Poppins', cursive;
            font-weight: 500;
            transition: all 0.2s ease;
        }

        .btn:hover {
            background-color: #028a11;
            transform: scale(1.05);
        }

        .logo {
            font-size: 3.5rem;
            font-weight: 800;
            color: var(--primary-color);
            margin-top: 1rem;
        }

        .logo span {
            font-style: italic;
            font-weight: 100;
            color: var(--secondary-color);
        }

        h1 {
            font-weight: 800;
            font-size: 4rem;
            display: inline;
            color: var(--secondary-color);
        }

        p {
            font-size: 1.5rem;
            color: var(--light-grey);
        }

        .loader {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            display: none;
        }

        .loader span {
            width: 15px;
            height: 15px;
            background: var(--primary-color);
            border-radius: 50%;
            animation: loading 0.8s infinite ease-in-out;
            margin: 0 5px;
        }

        .loader span:nth-child(1) { animation-delay: 0.1s; }
        .loader span:nth-child(2) { animation-delay: 0.2s; }
        .loader span:nth-child(3) { animation-delay: 0.3s; }
        .loader span:nth-child(4) { animation-delay: 0.4s; }

        @keyframes loading {
            0%, 100% { transform: translateY(0); }
            50% { transform: translateY(-15px); }
        }

        @media only screen and (max-width: 700px) {
            .logo { font-size: 2.5rem; }
            h1 { font-size: 2.5rem; }
            p { font-size: 1rem; margin-top: 1rem; padding: 0; }
            .btn { width: 12rem; height: 2.5rem; }
            .img-fluid { scale: 1.3; }
        }
    </style>

    <div class="container-fluid text-center d-flex flex-column align-items-center">
        <div class="loader">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>

        <div class="row mt-5">
            <div class="col-lg-7">
                <img src="{% static 'img/banner-img.png' %}" alt="Banner Image" class="img-fluid mt-3">
            </div>
            <div class="col-lg-5 mt-5">
                <div class="text-center logo mt-5">
                    <span>FOOD</span> <h1>COURT</h1>
                </div>
                <p class="mt-4">Democratising what you eat ;) Vote now for your favourite dishes!</p>
                <div class="d-flex flex-column justify-content-center align-items-center mt-4">
                    <a href="{% url 'users:f_login' %}" class="home">
                        <button class="btn mt-4">Log In</button>
                    </a>
                    {% comment %} <a href="{% url 'dishes:leaderboard' %}" class="home">
                        <button class="btn mt-4" style="background-color: var(--white); color: var(--secondary-color);">
                            <b>Skip</b>
                        </button>
                    </a> {% endcomment %}
                </div>
            </div>
        </div>
    </div>

    <!-- JavaScript Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <script src="{% static 'js/preloader.js' %}"></script>
</body>

</html>

templates/leaderboard2.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/final32.png' %}" type="image/x-icon">
    <title>FOOD COURT</title>
    <style>
        body {
            background-image: url("{% static 'img/background.png' %}");
        }

        span {
            font-style: italic;
            font-weight: 100;
        }

        #title {
            font-size: 5rem !important;
        }

        .gola {
            border-radius: 50%;
            height: 30px;
            width: 30px;
        }

        .normal {
            background-color: #343434 !important;
        }

        h6 {
            font-size: 30px;
        }

        @media only screen and (max-width: 700px) {
            #title {
                font-size: 4rem !important;
            }

            h4 {
                font-size: 1rem;
            }

            h6 {
                font-size: 25px;
            }
        }

        #menuToggle {
            display: block;
            position: relative;
            top: 50px;
            margin-left: 3rem;
            z-index: 100;
            user-select: none;
        }

        #menuToggle a {
            text-decoration: none;
            color: #232323;
            transition: color 0.3s ease;
        }

        #menuToggle a:hover {
            color: rgb(179, 67, 67) !important;
        }

        #menuToggle input {
            display: block;
            width: 40px;
            height: 32px;
            position: absolute;
            top: -7px;
            left: -5px;
            cursor: pointer;
            opacity: 0;
            z-index: 200;
            user-select: none;
        }

        #menuToggle span {
            display: block;
            width: 33px;
            height: 4px;
            margin-bottom: 5px;
            position: relative;
            background: #000000;
            border-radius: 3px;
            z-index: 1;
            transform-origin: 4px 0px;
            transition: transform 0.5s cubic-bezier(0.77, 0.2, 0.05, 1.0),
                background 0.5s cubic-bezier(0.77, 0.2, 0.05, 1.0),
                opacity 0.55s ease;
        }

        #menuToggle input:checked ~ span {
            opacity: 1;
            transform: rotate(45deg) translate(-2px, -1px);
            background: #232323;
        }

        #menuToggle input:checked ~ span:nth-last-child(2) {
            transform: rotate(-45deg) translate(0, -1px);
        }

        #menu {
            position: absolute;
            width: 250px;
            margin: -150px 0 0 -50px;
            padding: 50px;
            padding-top: 150px;
            background-image: linear-gradient(to top,rgba(0, 0, 0, 0.500),rgba(0, 0, 0, 0.297));
            list-style-type: none;
            transform-origin: 0% 0%;
            transform: translate(-100%, 0);
            transition: transform 0.5s cubic-bezier(0.77, 0.2, 0.05, 1.0);
        }

        #menu li {
            padding: 10px 0;
            font-size: 22px;
        }

        #menuToggle input:checked ~ ul {
            transform: none;
        }
        .btn-add-dish {
            display: inline-block;
            padding: 10px 20px;
            background-color: red;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            
        }
    
        .btn-add-dish:hover {
            background-color: darkgreen;
            color: white;
            
        }
    </style>
</head>
<body>

    <nav role="navigation">
        <div id="menuToggle">
            <input type="checkbox" />
            <span></span>
            <span></span>
            <span></span>
            <ul id="menu">
                {% comment %} <a href="#"><li>Home &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa-solid fa-house"></i></li></a>
                <a href="#"><li>Login &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa-solid fa-user"></i></li></a>
                <a href="#"><li style="color:rgb(179, 67, 67)">Leaderboard &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa-solid fa-trophy"></i></li></a>
                <a href="#"><li>Search More &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa-sharp fa-solid fa-magnifying-glass"></i></li></a> {% endcomment %}
                <a href="/logout"><li>Logout &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa-sharp fa-solid fa-arrow-right-from-bracket"></i></li></a>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h1 id="title" class="text-center mt-5">
            <span>FOOD</span>
            <div style="display: inline-block">COURT</div>
        </h1>
        <h6 class="text-center lb mb-5">Wednesday,29/10/2024</h6>
        <div class="d-flex justify-content-between">
        <a href="/add-dish" class="btn btn-add-dish">Add Dish</a>
        <a href="/hotel/add/" class="btn btn-add-dish">Add Hotel</a>
        <a href="{% url 'dishes:dish_graph' %}" class="btn btn-primary">View Graph</a>
        </div>

        <section id="rest">
            <div class="container-fluid mt-5">
                {% for dish in dish %}
                <div class="d-flex flex-column mt-5">
                    <a href="/dish_details/{{ dish.dish_Id }}" style="text-decoration: none; color: inherit;">
                        <div class="card-2">
                            <div class="row">
                                <div class="col-3">
                                    <h3>
                                        <div class="circle award-2 gola gold">&nbsp;1</div>
                                    </h3>
                                    <img src="{{ BASIC_DIR }}/uploads/{{dish.d_Photo}}" alt="dish_img" class="img-fluid p-2" style="width:110px; height: 110px;">
                                </div>
                                <div class="col-3 mt-5">
                                    <h4 style="white-space: nowrap;"> <b>{{dish.d_Name}}</b></h4>
                                </div>
                                <div class="col-3 mt-5" id="price">
                                    <h4>₹{{dish.d_Price}}</h4>
                                </div>
                                <div class="col-3">
                                    <div class="h-100 d-flex justify-content-between align-items-center">
                                        <h4 class="" style="white-space: nowrap;" id="votes">{{ dish.hotel.h_Name }}</h4>
                                        <i class="mr-auto fa-solid fa-sharp fa-3x fa-angle-up ar-red" style="margin-right: 3.5rem;"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </section>
    </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="{% static 'js/preloader.js' %}"></script>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>FOOD COURT</title>
    <link rel="icon" href="final32.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/final32.png' %}" type="image/x-icon">

</head>

<body>

    <style>
        body {
            background-image: none;
          
        
           overflow: hidden;
           overflow-y: scroll;
        
        }


        img {
            scale: 1.2;
        }

        .btn {
            width: 16rem;
            background-color: var(--success);
            border-radius: 16px;
            color: white;
            font-family: 'Poppins', cursive;
        }

        .logo {
            font-size: 4rem;
        }

        span {
            font-style: italic;
            font-weight: 100;



        }

        h1 {
            font-weight: 800;
            font-size: 4rem;
        }


        p {
            margin-top: 0rem;
            font-size: 1.5rem;
            padding: 2rem;
        }

        .btn {
            width: 20rem;
            height: 3rem;
        }
        
i{
    position: absolute;
    top: 5rem;
    left: 6rem;
}

a {
  text-decoration: none !important;
 
}
.border-bottom-only {
    border: none;
    border-bottom: 1px solid #000; /* Customize the color and thickness as needed */
    border-radius: 0;
}

        @media only screen and (max-width: 700px) {





            img {
                display: none;
            }



            h1 {
                font-weight: 800;
                font-size: 40px;
            }

            .logo {
                font-size: 40px;
            }

            .btn {
                width: 16rem;
                background-color: var(--success);
                border-radius: 16px;
                color: white;
                font-family: 'Poppins', cursive;
            }


            p {
                margin-top: 2rem;
                font-size: 1rem;
                padding: 0;
            }
            i{
           margin: 0;
           position: absolute;
           top: 4rem ;
           left: 2rem; 

        }
        h5{
            font-size: 0.9rem;
        }
        }
    </style>



    <div class="container-fluid d-block">
        <div class="loader">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        <a value="Previous Page" onClick="javascript:history.go(-1);" class="back">  <i class="fa-solid fa-angles-left float-start fa-lg "></i></a>
      
       
        
        <div class="row mt-5">
           
            <div class="col-lg-7 mt-5">
            
               
               
                <div class="  logo  mt-5">
                    
                 <div class="text-center">
                   
                 
                  <span >FOOD</span>

                    <div style="display: inline-block">
                        <h1 >COURT</h1>
                    </div>
                    <p style="color:var(--light-black)">Tired of the same old thing? let your stomach decide what you
                        eat</p>
                    </div>
                </div>
                <div class="text-center mt-4 p-2">


                    <h3 style="font-weight: 800;" class="mt-5 mx-5">Login now & eat what you vote for!</h2>

                </div>
                <div class="text-center d-flex  flex-column  align-items-center mt-2">
                    <form class="my-3" method="post">
                        {% csrf_token %}
                        <div class="form-group my-3 ">
                            <label for="text1" class="float-start my-3">E-mail Address:</label>
                            <input id="text1" name="email_address" type="text" class="form-control">
                        </div>
                        <div class="form-group my-5">
                            <label for="text" class="float-start my-3">Password</label>
                            <input id="text" name="password" type="password" class="form-control border-bottom-only">
                        </div>
                        
                        <div class="form-group my-3">
                            <button name="submit" type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
<h5 class="text-center mt-1" style="color: var(--light-black);">Dont have an account <a href="{% url 'users:f_sign_up' %}" style="color:black ;"><u>Sign Up</u></a> now!</h5>
                </div>

            </div>

            <div class="sign up col-lg-5">
                <img src="{% static 'img/login.png' %}" alt="" class="img-fluid mt-3">

            </div>
        </div>

    </div>


















    <!-------javascript bundle----->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>

    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="{% static 'js/preloader.js' %}"></script>

</body>

</html>